### ISSUE TITLE
Twice rendering with nextjs

### ISSUE THREAD

**Issue by xbeakmanx** [bumbag/bumbag-ui#103]
**Describe the bug**
The application is rendering twice when isSSR is enabled in BumbagProvider.

**To Reproduce**
follow the [getting started](https://bumbag.style/getting-started/) and: 

![Screen_Shot_2020-11-19_at_11 14 38_AM](https://user-images.githubusercontent.com/60238989/109670417-17f5af80-7b41-11eb-8c81-272997eae031.png)

![Screen_Shot_2020-11-19_at_11 17 15_AM](https://user-images.githubusercontent.com/60238989/109670392-1330fb80-7b41-11eb-9407-aa654dd75fe6.png)

![Screen_Shot_2020-11-19_at_11 14 18_AM](https://user-images.githubusercontent.com/60238989/109670504-2c39ac80-7b41-11eb-83e7-fd5e5c02199b.png)

**Expected behavior**

The useEffect should run once

**Comment by Arithmetics** [comment]
same for me

**Comment by Chrischuck** [comment]
After emotion 11 upgrade gets merged in, I'll take a look at this. We can _probably_ remove the extra steps around ssr since emotion 11 supports ssr out of box. My testing has shown that I don't need the extra steps either.

So hopefully this problem will be a non issue soon but I'll verify after the pr gets merged :)

**Comment by deivijt** [comment]
any update about this?  
We have the latest version of bumbag but there is still a twice rendering problem

**Comment by jxom** [comment]
This should be fixed in `1.11.5`

**Comment by deivijt** [comment]
The issue still persists with the version 1.11.5  of bumbag
<img width="1404" alt="Screen Shot 2021-03-23 at 4 48 21 PM" src="https://user-images.githubusercontent.com/6088018/112223195-95b85280-8bf7-11eb-80bf-71bbf8b5d0e4.png">

**Comment by jxom** [comment]
Can you try `1.11.6` now?

**Comment by deivijt** [comment]
Nice.  issue resolved. thank you!!
